{
 "title": "Knative Custom Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Custom Perf Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cold Start Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready_time - kube_pod_status_scheduled_time { namespace = 'default'}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Request Rate per Sec (  5m )",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (configuration_name) (rate(revision_app_request_count {namespace_name = 'default'} [5m]))",
     "legendFormat": "{{configuration_name}}"
    }
   ]
  },
  {
   "title": "app_request_latencies (90) in millis",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(revision_app_request_latencies_bucket { namespace_name = 'default'}[1m])) by (le))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "app_request_latencies (90) in millis",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(revision_app_request_latencies_bucket { namespace_name = 'default'}[1m])) by (le))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "inmemorychannel_dispatcher_event_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (event_type) (rate(inmemorychannel_dispatcher_event_count {event_type != 'Audit'} [5m]))",
     "legendFormat": "{{event_type}}"
    }
   ]
  },
  { "title": "Autoscaler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Desired Pod",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (configuration_name) (autoscaler_desired_pods { namespace_name = 'default'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requested Pod",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (configuration_name) (autoscaler_requested_pods { namespace_name = 'default'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Actual Pod",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (configuration_name) (autoscaler_actual_pods { namespace_name = 'default'})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}